exports.up = async function(pgm) {
  await pgm.sql(`
    INSERT INTO dependency_catalog (ecosystem, language, framework, file_names, dependency_field) VALUES
    ('kotlin', 'Kotlin', 'Spring', ARRAY['build.gradle.kts', 'build.gradle', 'pom.xml'], NULL),
    ('kotlin', 'Kotlin', 'Android', ARRAY['build.gradle.kts', 'build.gradle'], NULL),
    ('kotlin', 'Kotlin', 'Ktor', ARRAY['build.gradle.kts', 'build.gradle'], NULL),
    ('kotlin', 'Kotlin', NULL, ARRAY['build.gradle.kts', 'build.gradle', 'pom.xml'], NULL),
    ('objc', 'Objective-C', 'UIKit', ARRAY['Podfile', 'Cartfile'], NULL),
    ('cocoapods', 'Objective-C', NULL, ARRAY['Podfile'], NULL),
    ('carthage', 'Swift', NULL, ARRAY['Cartfile'], NULL),
    ('swift-pm', 'Swift', 'Vapor', ARRAY['Package.swift'], NULL),
    ('swift-pm', 'Swift', 'UIKit', ARRAY['Package.swift'], NULL),
    ('swift-pm', 'Swift', NULL, ARRAY['Package.swift'], NULL),
    ('npm', 'TypeScript', 'Next.js', ARRAY['package.json'], 'dependencies'),
    ('npm', 'TypeScript', 'NestJS', ARRAY['package.json'], 'dependencies'),
    ('npm', 'TypeScript', 'Svelte', ARRAY['package.json'], 'dependencies'),
    ('npm', 'TypeScript', 'Remix', ARRAY['package.json'], 'dependencies'),
    ('npm', 'TypeScript', 'Astro', ARRAY['package.json'], 'dependencies'),
    ('npm', 'TypeScript', NULL, ARRAY['package.json', 'yarn.lock', 'pnpm-lock.yaml'], 'dependencies'),
    ('npm', 'JavaScript', 'React Native', ARRAY['package.json'], 'dependencies'),
    ('npm', 'JavaScript', 'Electron', ARRAY['package.json'], 'dependencies'),
    ('pip', 'Python', 'Pytest', ARRAY['requirements.txt', 'pyproject.toml'], NULL),
    ('pip', 'Python', 'Jupyter', ARRAY['requirements.txt', 'pyproject.toml'], NULL),
    ('pip', 'Python', 'Pandas', ARRAY['requirements.txt', 'pyproject.toml'], NULL),
    ('pip', 'Python', 'NumPy', ARRAY['requirements.txt', 'pyproject.toml'], NULL),
    ('pip', 'Python', 'Scikit-learn', ARRAY['requirements.txt', 'pyproject.toml'], NULL),
    ('pip', 'Python', 'TensorFlow', ARRAY['requirements.txt', 'pyproject.toml'], NULL),
    ('pip', 'Python', 'PyTorch', ARRAY['requirements.txt', 'pyproject.toml'], NULL),
    ('go', 'Go', 'Fiber', ARRAY['go.mod'], NULL),
    ('go', 'Go', 'Chi', ARRAY['go.mod'], NULL),
    ('go', 'Go', 'gRPC', ARRAY['go.mod'], NULL),
    ('cargo', 'Rust', 'Tokio', ARRAY['Cargo.toml'], NULL),
    ('cargo', 'Rust', 'Rocket', ARRAY['Cargo.toml'], NULL),
    ('cargo', 'Rust', 'Serde', ARRAY['Cargo.toml'], NULL),
    ('maven', 'Java', 'Quarkus', ARRAY['pom.xml'], NULL),
    ('maven', 'Java', 'Micronaut', ARRAY['pom.xml'], NULL),
    ('gradle', 'Java', 'Android', ARRAY['build.gradle', 'build.gradle.kts'], NULL),
    ('gradle', 'Kotlin', 'Android', ARRAY['build.gradle', 'build.gradle.kts'], NULL),
    ('nuget', 'C#', 'ASP.NET', ARRAY['*.csproj'], NULL),
    ('nuget', 'C#', 'Xamarin', ARRAY['*.csproj'], NULL),
    ('nuget', 'C#', 'MAUI', ARRAY['*.csproj'], NULL),
    ('nuget', 'F#', NULL, ARRAY['*.fsproj'], NULL),
    ('composer', 'PHP', 'Symfony', ARRAY['composer.json'], NULL),
    ('composer', 'PHP', 'WordPress', ARRAY['composer.json'], NULL),
    ('pub', 'Dart', 'GetX', ARRAY['pubspec.yaml'], NULL),
    ('pub', 'Dart', 'Bloc', ARRAY['pubspec.yaml'], NULL),
    ('conan', 'C++', NULL, ARRAY['conanfile.txt', 'conanfile.py'], NULL),
    ('vcpkg', 'C++', NULL, ARRAY['vcpkg.json'], NULL),
    ('cmake', 'C++', NULL, ARRAY['CMakeLists.txt'], NULL),
    ('sbt', 'Scala', 'Play', ARRAY['build.sbt'], NULL),
    ('sbt', 'Scala', 'Akka', ARRAY['build.sbt'], NULL),
    ('sbt', 'Scala', NULL, ARRAY['build.sbt'], NULL),
    ('mix', 'Elixir', 'Phoenix', ARRAY['mix.lock'], NULL),
    ('mix', 'Elixir', NULL, ARRAY['mix.lock'], NULL),
    ('bundler', 'Ruby', 'Rails', ARRAY['Gemfile'], NULL),
    ('bundler', 'Ruby', 'Sinatra', ARRAY['Gemfile'], NULL),
    ('bundler', 'Ruby', NULL, ARRAY['Gemfile'], NULL),
    ('leiningen', 'Clojure', NULL, ARRAY['project.clj'], NULL),
    ('deps-edn', 'Clojure', NULL, ARRAY['deps.edn'], NULL),
    ('hal', 'Kotlin', 'Multiplatform', ARRAY['build.gradle.kts'], NULL),
    ('spm', 'Swift', 'Combine', ARRAY['Package.swift'], NULL)
  `);
};

exports.down = async function(pgm) {
  await pgm.sql("DELETE FROM dependency_catalog WHERE ecosystem IN ('kotlin', 'objc', 'cocoapods', 'carthage', 'conan', 'vcpkg', 'cmake', 'sbt', 'mix', 'bundler', 'leiningen', 'deps-edn', 'hal', 'spm')");
};
